### ISSUE TITLE
Warning on failed format

### ISSUE THREAD

**Issue by Roald87** [STweep/STweep#12]
When trying to format the following code which contains an error (missing semicolon)

```
var2:=2;
var1:= 1 
```

no formatting is done. It would be nice if there is some sort of pop-up why no formatting was done. 

When I was trying to format some code earlier, it didn't do anything and it took me a minute before I realized there was a missing semicolon.

**Comment by HAHermsen** [comment]
No shouldn't the code be compiled first before formatting?
Otherwise the formatter will change into a semi compiler itself..

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Roald87** [comment]
Not that I know.

**Comment by Barteling** [comment]
STweep does not rely on any other parser/compiler for the formatting process then it's own. 

I considered giving a warning if not all text can be parsed and thus formatted, but I did not decide on that yet.
Other formatters i personally work with like resharper are also not showing warnings if they cannot format all code.

**Comment by Roald87** [comment]
I think it would be useful.

**Comment by HAHermsen** [comment]
My opinion;
Forgetting a semi-colomn is not formatting issue, so there is no point of point of a generating warning in STweep.
Plus, the compiler will see this as an error and report it as such so you can correct it manually.
I think STweep should only "reformat"  and not "auto-correct" source-code (auto-correct as in remove compiler errors).

Therefore;
Any errors present in the sourcecode before using STweep should present after STweep has finished reformatting.

**Comment by Barteling** [comment]
improved in 4.1.0-Beta
https://www.stweep.com/beta-releases/
